Repository UCD-SERG/serocalculator, pull requests merged in 2024-08, with the labels that each got.

#226 Improve as curve params error messaging
  R/as_curve_params.R
  tests/testthat/test-as_curve_params.R
Labels: enhancement, API

#155 Readme edits
  README.md
  README.qmd
Labels: documentation

#240 lint PRs
  .github/workflows/lint-changed-files.yaml
Labels: CI
