Repository UCD-SERG/serocalculator, pull requests merged in 2024-07, with the labels that each got.

#158 set GitHub actions to treat warnings in test as errors
  .github/workflows/R-CMD-check.yaml
  tests/testthat.R
Labels: bug

#175 add light-switch to pkgdown page
  _pkgdown.yml
Labels: enhancement

#173 added `verbose` option for check_pop_data.
  DESCRIPTION
  NEWS.md
  R/check_pop_data.R
  man/check_pop_data.Rd
  vignettes/articles/enteric_fever_example.Rmd
  vignettes/articles/scrubTyphus_example.Rmd
Labels: enhancement

#183 ignore readme source file and codecov config file
  .Rbuildignore
  DESCRIPTION
Labels: documentation

#189 updating instances of deprecated function names
  R/llik.R
  R/sim.cs-utils.r
  man/llik.Rd
  man/mkbaseline.Rd
  vignettes/articles/simulate_xsectionalData.Rmd
Labels: bug

#176 Test stratify data
  DESCRIPTION
  NEWS.md
  R/curve_param_names.R
  R/est.incidence.R
  R/est.incidence.by.R
  R/noise_param_names.R
  R/stratify_data.R
  inst/WORDLIST
  man/est.incidence.Rd
  man/est.incidence.by.Rd
  man/stratify_data.Rd
  tests/testthat/_snaps/stratify_data.md
  tests/testthat/test-stratify_data.R
Labels: enhancement

#195 avoid workspace issues on restart
  serocalculator.Rproj
Labels: infrastructure

#193 unscramble lifecycle information
  R/get_additional_data.R
  man/get_additional_data.Rd
Labels: bug

#198 add biomarker colname meta-data and associated methods
  NAMESPACE
  R/as_pop_data.R
  R/load_pop_data.R
  man/as_pop_data.Rd
  man/load_pop_data.Rd
Labels: backend

#203 remove old MD5
  MD5
Labels: tech debt

#188 as curve params
  NAMESPACE
  R/as_curve_params.R
  R/load_curve_params.R
  man/as_curve_params.Rd
Labels: enhancement

#204 use @noRd to document internal functions
  R/df_to_array.R
  man/df_to_array.Rd
Labels: documentation

#207 improving `check_pop_data()`
  R/check_pop_data.R
  man/check_pop_data.Rd
  tests/testthat/test-check_pop_data.R
Labels: API, unit testing

#216 make `cli` usage more consistent
  R/load_pop_data.R
Labels: modernization, API

#215 add as_curve_params test
  R/as_curve_params.R
  tests/testthat/_snaps/as_curve_params.md
  tests/testthat/test-as_curve_params.R
Labels: unit testing
